## Site metadata ##

title: MéninGIT - guide visuel pour utiliser git vite et bien
description: Guide visuel en français pour utiliser git vite et bien

### Built settings ###

url: "https://roxanebellot.github.io"
baseurl: "/meninGIT"

github_username: roxanebellot

theme: minima
