## Site metadata ##

title: MéninGIT - Guide en français pour les pressés.
description: Guide visuel en français pour utiliser git vite et bien

### Built settings ###

url: "http://127.0.0.1:4000"
baseurl: "/meningit"

github_username: roxanebellot

theme: just-the-docs

search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Problème ? Suggestion ?":
    - "/meningit/about.html"
