## Site metadata ##

title: MéninGIT - Guide en français pour les pressés.
description: Guide visuel en français pour utiliser git vite et bien

### Built settings ###

url: "https://roxanebellot.github.io"
baseurl: "/meninGIT"

github_username: roxanebellot

theme: just-the-docs

search_enabled: true